import requests
from flask import Flask, request

app = Flask(__name__)

CLIENT_ID = '1459208723686756525'
CLIENT_SECRET = '3vJLZO-I7oDTi_5fJcoebyKxUeDOjDGj'
REDIRECT_URI = 'http://localhost:5000/callback'

@app.route('/callback')
def callback():
    # 1. Get the 'code' from Discord's redirect
    auth_code = request.args.get('code')
    
    # 2. Exchange the code for an Access Token and Webhook info
    data = {
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET,
        'grant_type': 'authorization_code',
        'code': auth_code,
        'redirect_uri': REDIRECT_URI
    }
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    
    response = requests.post('https://discord.com/api/v10/oauth2/token', data=data, headers=headers)
    token_data: dict= response.json()

    # 3. Extract the Webhook URL
    # This is automatically generated by Discord during the auth flow
    webhook_info: dict= token_data.get('webhook', {})
    webhook_url = webhook_info.get('url')

    if webhook_url:
        return f"Success! Save this URL for your sensor: {webhook_url}"
    else:
        return "Failed to create webhook.", 400

if __name__ == '__main__':
    app.run(port=5000)